<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CatalogosSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('catalogos')->insert([
            [
            'catalogo' => '2201001001',
            'nombre' => 'Alim. Agua Purificada',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de bidones de agua y el arriendo de la máquina que los provee, los cuales están destinados al consumo de seres humanos. Se incluyen aquí también el uso de máquinas que purifican agua.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001002',
            'nombre' => 'Alim. Reunión Corte Apelación, Suprema y Consejo Cord Zonal',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de alimentos, destinados al consumo de participantes de las reuniones de Cortes de Apelaciones del país, del Pleno de la Corte Suprema y para la preparación de colaciones1 de los Ministros, además de las reuniones de Consejo de Coordinación Zonal.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001003',
            'nombre' => 'Alim. Reunión Comite Paritario',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de alimentos destinados al consumo de participantes de las reuniones de Comité Paritario.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001004',
            'nombre' => 'Alim. Reunión Consejo de Bienestar',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de alimentos destinados al consumo de participantes de las reuniones de Consejo de Bienestar.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001005',
            'nombre' => 'Alim. Capacitación Comité Paritario',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de alimentos por servicios de coffee break en capacitaciones de Comités Paritarios.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001006',
            'nombre' => 'Alim. Reunión Departamentos o Administraciones Zonales',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de alimentos destinados al consumo de participantes de las reuniones internas Departamentales o de Administraciones Zonales.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001007',
            'nombre' => 'Alim. Compensatorio Oficial Asistente Ministro',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de alimentos destinados a oficiales asistentes de Ministros.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2201001008',
            'nombre' => 'Alim. Otros',
            'descripcion' => 'Son los gastos por concepto de adquisición de otros alimentos no contemplados en las otras subasignaciones.',
            'item' => 2201,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2202001000',
            'nombre' => 'Textiles y Acabados Textiles',
            'descripcion' => 'Son los gastos por concepto de adquisiciones y/o confecciones de hilados y telas de cualquier naturaleza. Incluye, además, los gastos por concepto de teñidos de telas y similares.',
            'item' => 2202,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2202002000',
            'nombre' => 'Vestuario, Accesorios y Prendas Diversas',
            'descripcion' => 'Son los gastos por concepto de adquisiciones y/o confecciones de uniformes, elementos de protección para el vestuario, prendas de vestir para usos agrícolas e industriales, ropa para escolares y demás artículos de naturaleza similar. Incluye gastos que originan la readaptación o transformación del vestuario.',
            'item' => 2202,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2202003000',
            'nombre' => 'Calzado',
            'descripcion' => 'Son los gastos por concepto de adquisiciones y/o confecciones de calzado de cualquier naturaleza, incluidos los de tela, caucho y plástico. Incluye, además, las adquisiciones de los materiales necesarios para la reparación de calzado.',
            'item' => 2202,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001001',
            'nombre' => 'Comb. Vehiculo Pdte. Supremo / Ministro / Fiscal / Director',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de combustibles y lubricantes para el consumo de vehículos asignados a Ministro, Fiscal, Director CAPJ y Presidente Supremo, para las diversas unidades Judiciales del país.',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001002',
            'nombre' => 'Comb. Vehiculo Capj',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de combustibles y lubricantes para el consumo de vehículos asignados a las distintas CAPJ.',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001003',
            'nombre' => 'Comb. Reembolso',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de combustibles y lubricantes por reembolsos en cometido; en este sentido se exceptúan los gastos por reembolso de combustible de los cometidos de funcionarios por cursos de la Academia Judicial, que se imputarán en el catálogo 22.03.001.005.',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203001004',
            'nombre' => 'Comb. Vehiculos Otros',
            'descripcion' => 'Son los gastos por concepto de adquisición de combustible para vehículos no contemplados en las otras subasignaciones.',
            'item' => 2203,
            'estado' => 'Activo',
        ],
         [
            'catalogo' => '2203001005',
            'nombre' => 'Comb. Reembolso Academia Judicial',
            'descripcion' => 'Son los gastos por concepto de reembolsos de combustible, solo para funcionarios asistentes a los cursos de la Academia Judicial en cumplimiento de labores del servicio.',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203002000',
            'nombre' => 'Para Maquinarias, Equipos de Producción,Tracción y Elevación',
            'descripcion' => 'Para Maquinarias, Equipos de Producción,Tracción y Elevación',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203003000',
            'nombre' => 'Para Calefacción',
            'descripcion' => 'Para Calefacción',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2203999000',
            'nombre' => 'Para Otros',
            'descripcion' => 'Para Otros',
            'item' => 2203,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204001000',
            'nombre' => 'Materiales de Oficina',
            'descripcion' => 'Comprende los gastos por concepto de adquisiciones de: – Productos de Papeles, Cartones e Impresos y, en general, todo tipo de formularios e impresos y demás productos de esta naturaleza necesarios para el uso o consumo de oficinas. Incluye, además, materiales para impresión, y en general, todo tipo de productos químicos necesarios para el uso o consumo de oficinas.
– Materiales y Útiles Diversos de Oficina y, en general, toda clase de artículos de naturaleza similar para el uso o consumo de oficinas.
– Materiales y Útiles Diversos de Impresión, no incluidos anteriormente, necesarios para el uso o consumo en unidades de impresión que mantengan las distintas reparticiones de los Servicios Públicos.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204002000',
            'nombre' => 'Textos y Otros Materiales de Enseñanza',
            'descripcion' => 'Comprende los gastos por concepto de adquisiciones de: Materiales Básicos de Enseñanza, tales como cuadernos, papeles de dibujos, de impresión, calco, recortes, libros de estudios y para bibliotecas, láminas, mapas, y, en general todo producto de naturaleza similar necesario para el uso o consumo de los establecimientos de educación en general, excluyéndose todo material de este tipo necesario para labores administrativas en los establecimientos. Incluye, además, las adquisiciones de productos químicos que sean destinados exclusivamente a la enseñanza y la adquisición de almácigos, semillas, plantas, árboles, minerales, hojalatas, láminas, planchas y planchones de acero, platinos, cañerías, productos de cobre, zinc, bronce, etc., alambre, artículos de cerrajería y demás materiales de naturaleza similar que se destinen exclusivamente a la enseñanza. Incluye, asimismo, la adquisición de libros y revistas de carácter técnico, láminas, mapas y otros similares, para los organismos del Sector Público. Otros Materiales y Útiles diversos de Enseñanza de Deportes y Varios del Ramo, tales como herramientas menores, tiza, reglas, transportadores, compases, punteros para pizarrones, lápices, gomas, etc., artículos e implementos deportivos, artículos de recreación y otros de naturaleza similar. Además, se incluyen por este concepto los animales necesarios para la investigación cuando se destinan para uso exclusivo de la enseñanza.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204004000',
            'nombre' => 'Productos Farmacéuticos',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de vitaminas y preparados vitamínicos, productos bacteriológicos, sueros, vacunas, penicilina, estreptomicina y otros antibióticos, cafeína y otros alcaloides opiáceos; productos apoterápicos como plasma humano, insulina, hormonas, medicamentos preparados para uso interno y externo, productos para cirugía y mecánica dental, materiales de curación y otros medicamentos y productos farmacéuticos.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204007000',
            'nombre' => 'Materiales y Útiles de Aseo',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de todo producto destinado a ser consumido o usado en el aseo de las reparticiones del Sector Público.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204008000',
            'nombre' => 'Menaje para Oficina, Casino y Otros',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de artículos tales como ceniceros, cuchillería, batería de cocina, candados, platos, vasos, botellas, azucareros, bandejas, alcuzas y demás artículos de esta naturaleza necesarios para el uso en oficinas, casinos y otras dependencias de las reparticiones públicas.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204009000',
            'nombre' => 'Insumos, Repuestos y Accesorios Computacionales',
            'descripcion' => 'Son los gastos por adquisiciones de insumos y/o suministros necesarios para el funcionamiento de los equipos informáticos, tales como cintas, discos, disquetes, papel para impresoras, etc.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204010000',
            'nombre' => 'Materiales para Mantenimiento y Reparaciones de Inmuebles',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de artículos refractarios, vidrios, ladrillos, cemento, yeso, cal, baldosas, mosaicos, bloques y pastelones de cemento, codos, cañerías y fitting, materiales para pintar y barnizar, materiales de cerrajería, maderas, artículos eléctricos, productos aislantes y de impermeabilización, pegamentos, colas, anticorrosivos, desincrustantes, explosivos, papeles decorativos y, en general, todo artículo de naturaleza similar necesario para la mantención y reparación de las reparticiones de los organismos del Sector Público.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204011000',
            'nombre' => 'Repuestos y Accesorios para Manten. y Reparacion de Vehículo',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de neumáticos, cámaras, baterías, rodamientos, ejes, piñones, diferenciales, materiales eléctricos, pistones, bloques, motores, bujías, faroles, espejos, vidrios y, en general, todo material de esta naturaleza necesario para la mantención y reparación de vehículos motorizados.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204012000',
            'nombre' => 'Otros Materiales, Repuestos y Útiles Diversos para Mantenimi',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de herramientas, materiales, repuestos y otros útiles necesarios para la mantención, seguridad y reparación de bienes inmuebles, instalaciones, maquinarias y equipos no incluidos en los rubros anteriores.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204013000',
            'nombre' => 'Equipos Menores',
            'descripcion' => 'Son los gastos por concepto de adquisiciones de equipos e implementos menores diversos para uso institucional.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204014000',
            'nombre' => 'Productos Elaborados de Cuero, Caucho y Plásticos',
            'descripcion' => 'Son los gastos por concepto de adquisición de productos elaborados de cuero, caucho y plásticos, tales como pieles, cueros, curtidos y por curtir, bolsas, correas, monturas y otros productos de talabartería (a excepción de calzado, carteras y otras prendas de vestir), artículos de caucho tales como mangueras, cojines, etc. (a excepción de neumáticos y cámaras para vehículos motorizados), bolsas de polietileno y artículos de plásticos varios.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204015000',
            'nombre' => 'Productos Agropecuarios y Forestales',
            'descripcion' => 'Son los gastos por concepto de adquisición de productos agropecuarios y forestales necesarios para la confección y mantenimiento de jardines, campos deportivos, y otros de similar naturaleza.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204999001',
            'nombre' => 'Certificados Digitales',
            'descripcion' => 'Este catálogo es de uso exclusivo del Departamento de Informática y Computación del Poder Judicial. Dispositivos criptográficos para firma electrónica y digital avanzada.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2204999002',
            'nombre' => 'Otros',
            'descripcion' => 'Son los gastos por concepto de adquisición de otros materiales de uso o consumo no contemplados en las asignaciones anteriores.',
            'item' => 2204,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205001000',
            'nombre' => 'Electricidad',
            'descripcion' => 'En esta asignación se incluirán, además, los gastos por concepto de los consumos de energía eléctrica del alumbrado público.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205002000',
            'nombre' => 'Agua',
            'descripcion' => 'En esta asignación se imputarán, además, los gastos por concepto de consumos de agua potable, derechos de agua, compra de agua a particulares y otros análogos, destinados al regadío de parques y jardines de uso público, así como el gasto asociado a los consumos de grifos.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205003000',
            'nombre' => 'Gas',
            'descripcion' => 'Gas',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205004001',
            'nombre' => 'Correo Normal',
            'descripcion' => 'Son los gastos por concepto de servicio de correo.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205004002',
            'nombre' => 'Correo Arriendo de Casilla',
            'descripcion' => 'Son los gastos por concepto de arriendos de apartados postales.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205005000',
            'nombre' => 'Telefonía Fija',
            'descripcion' => 'Telefonía Fija',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205006001',
            'nombre' => 'Telefonía Celular Cuota Fija',
            'descripcion' => 'Son los gastos relacionados al valor mensual de los planes contratados para uso de telefonía celular del Poder Judicial.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205006002',
            'nombre' => 'Telefonía Celular Compra de Equipos Celulares',
            'descripcion' => 'Este catálogo es de uso exclusivo del Nivel Central de la CAPJ. Adquisición de equipos celulares para uso de funcionarios del Poder Judicial.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205006003',
            'nombre' => 'Telefonía Celular Recarga de Equipo Satelital',
            'descripcion' => 'Corresponde a la recarga de los equipos satelitales de uso del Poder Judicial, exclusivo del Nivel Central de la CAPJ.Se incluye la recarga de equipos celulares, para casos excepcionales, previa autorización del Nivel Central de la CAPJ',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205007000',
            'nombre' => 'Acceso a Internet',
            'descripcion' => 'Son los gastos por concepto de uso del servicio de Internet, referidos a cobros fijos o variables según el consumo.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205008000',
            'nombre' => 'Enlaces de Telecomunicaciones',
            'descripcion' => 'Son los gastos por contratación de líneas de comunicación con redes o bases de datos públicos y privados, a través de microondas, radiofrecuencia, fibra óptica, satélite, etc. Incluye tanto los gastos de instalación como el costo fijo o variable determinado en el contrato.',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2205999000',
            'nombre' => 'Otros',
            'descripcion' => 'Otros',
            'item' => 2205,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001001',
            'nombre' => 'Cerrajería',
            'descripcion' => 'Son los gastos por concepto de instalación y reparación de cerrajerías a puertas y portones de edificios para oficinas públicas.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001002',
            'nombre' => 'Gasfitería',
            'descripcion' => 'Son los gastos por concepto de gastos por trabajos de gasfitería en edificios y unidades Judiciales del país.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001003',
            'nombre' => 'Otras Reparaciones - Edificaciones',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de edificios y unidades Judiciales del país, no contemplados en las otras subasignaciones.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001004',
            'nombre' => 'Mant. y Rep. Camaras Alcantarillado - Sanitarias',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de cámaras de alcantarillado y/o sanitarias de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001005',
            'nombre' => 'Mant. y Rep. Ascensor',
            'descripcion' => 'Son los gastos por concepto de instalación, mantenimiento y reparación de ascensores de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de ascensores.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001006',
            'nombre' => 'Mant. y Rep. de Estanques',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de estanques de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de estanques.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001007',
            'nombre' => 'Mant. y Rep. Módulos Fotovoltaicos',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de módulos fotovoltaicos de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de módulos fotovoltaicos.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001008',
            'nombre' => 'Mant. y Rep. Salvaescalera',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de salvaescalera de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de salvaescalera.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001009',
            'nombre' => 'Mant. y Rep. Tablero Eléctrico',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de los tableros eléctricos de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de tableros eléctricos.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001010',
            'nombre' => 'Mant. y Rep. Techumbre / Canaleta',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de techumbre y canaleta de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de techumbres y/o canaletas.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001011',
            'nombre' => 'Mant. Y Rep. Red Húmeda y seca',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de la red húmeda y seca de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001012',
            'nombre' => 'Mant. y Rep. Sist. Eléctrico / Iluminación',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de sistemas eléctricos e iluminación de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de sistema eléctrico y/o iluminación.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001013',
            'nombre' => 'Mant. y Rep. Aire Acondicionado',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de aire acondicionado o equipos de climatización de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de equipos de aire acondicionado.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001014',
            'nombre' => 'Mant. y Rep. Sistema de Calefacción',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de sistema de calefacción de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de Calefacción.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001015',
            'nombre' => 'Mant. y Rep. Calderas',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de calderas de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de calderas.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001016',
            'nombre' => 'Mant. y Rep. Bombas de Elevación de Agua',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de bombas de elevación de agua de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo.Incluye instalación y desmontaje de bombas de elevación de agua.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001017',
            'nombre' => 'Mant. y Rep. Grupo Electrógeno',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de grupos electrógenos de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de grupos electrógenos.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001018',
            'nombre' => 'Mant. Y Rep. Control Acceso',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación del sistema control de acceso vehicular y peatonal de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de controles de acceso, ya sean vehiculares o peatonales.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001020',
            'nombre' => 'Obras de Habilitaciones',
            'descripcion' => 'Son los gastos por concepto de obras en habilitación menor en edificios y unidades Judiciales del país, no contempladas en las iniciativas de inversión contenidas en el Subtítulo 31.El uso de esta cuenta es para iniciativas operacionales autorizadas por el Nivel Central de la CAPJ, además también se podrán considerar como redistribuciones según sea la necesidad del requirente, con la tipología COPT OC RDGV 0000 con un Autofinanciamiento.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206001021',
            'nombre' => 'Pinturas Edificaciones',
            'descripcion' => 'Son los gastos por obras de pinturas exterior e interior, en edificios y unidades Judiciales del país, no contempladas en las iniciativas de inversión contenidas en el Subtítulo 31 por conservación de edificaciones.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206002000',
            'nombre' => 'Mantenimiento y Reparación de Vehículos',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de automóviles, autobuses, camiones, jeep, motos, vehículos de tres ruedas, de equipos ferroviarios, marítimos y aéreos, y de equipos de tracción animal y mecánica.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206003000',
            'nombre' => 'Mantenimiento y Reparación de Mobiliarios y Otros',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de mobiliario de oficinas y viviendas, muebles de instalaciones militares, policiales, educacionales, sanitarias y hospitalarias, de Aduana, puertos y aeropuertos, etc.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004001',
            'nombre' => 'Mant. y Rep. Portón Eléctrico',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de portón eléctrico de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de portones eléctricos.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004002',
            'nombre' => 'Mant. y Rep. Central Telefónica',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de la central telefónica para las unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de centrales telefónicas.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004003',
            'nombre' => 'Mant. y Rep. Equipos Audio',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de los equipos de audio de los edificios y unidades Judiciales del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de equipos de audio.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004005',
            'nombre' => 'Mant. y Rep. Detector de Metales / Rayos X',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de detector de metales y/o equipos rayos X de las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de equipos detectores de metales y/o rayos X.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004006',
            'nombre' => 'Mant. y Rep. Sistema Detección de Incendio',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de sistema detección de incendio de las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de sistemas de detección de incendios.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004007',
            'nombre' => 'Mant. y Rep. Alarmas',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de sistema alarma de las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de sistemas de alarmas.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004008',
            'nombre' => 'Mant. y Rep. CCTV',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de circuito cerrado de televisión "CCTV" de las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de CCTV.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004009',
            'nombre' => 'Mant. y Recarga Extintores',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de extintores de las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación, desmontaje y recarga de extintores.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206004010',
            'nombre' => 'Otras Reparaciones Menores de Maq. y Eq. de Oficina',
            'descripcion' => 'Son los gastos por concepto de otras mantenciones y reparaciones menores de máquinas y equipos de oficina de las unidades Judiciales del país, no contemplados en las otras subasignaciones. Incluye instalación y desmontaje.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206006000',
            'nombre' => 'Mantenimiento y Reparación de Otras Maquinarias y Equipos',
            'descripcion' => 'Comprende los gastos por concepto de mantenimiento y reparaciones de:– Equipos Médicos, Sanitarios y de Investigación, tales como equipos de Rayos X, equipos dentales, aparatos de medición, equipos de laboratorios, etc. – Mantenimiento y Reparación de Máquinas y Equipos Viales destinados a la construcción y/o mantenimiento de calles, caminos, construcción de puentes y otras obras que forman parte de los procesos de construcción y mantenimiento vial. – Mantenimiento y Reparación de Máquinas y Equipos de Construcción dedicados a la construcción de edificios, obras de infraestructura, instalaciones adheridas a edificios y al suelo, a excepción de los equipos viales.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007001',
            'nombre' => 'Mant. y Rep. Sistemas Computacionales',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de los sistemas computacionales de exclusivo uso informático, para las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Se incluye en esta subasignación las mantenciones de domótica.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007002',
            'nombre' => 'Mant. y Rep. Tottem',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de los tótems computacionales, para las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de tótem computacionales.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007003',
            'nombre' => 'Mant. y Rep. Fotocopiadora',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de fotocopiadoras computacionales, para las unidades Judiciales y de administración del país.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007004',
            'nombre' => 'Mant. y Rep. Escáner Computacionales',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de escáneres computacionales de exclusivo uso informático, para las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje de escáner computacionales.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007005',
            'nombre' => 'Mant. y Rep. Tarjetas de Accesos',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de sistemas de tarjetas de control de accesos computacionales, para las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007006',
            'nombre' => 'Mant. y Rep. Impresoras, Multifuncionales y Ploter',
            'descripcion' => 'Son los gastos por concepto de otras mantenciones y reparaciones de equipos computacionales (impresoras, multifuncionales y plotter) de exclusivo uso informático, para las unidades Judiciales y de administración del país.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007007',
            'nombre' => 'Mant. y Rep. Puntos de Red, de Voz y Datos',
            'descripcion' => 'Son los gastos por concepto de reparación y/o habilitación de cableados de puntos de red, de voz y datos, para las unidades Judiciales y de administración del país, ya sean de carácter correctivo o preventivo. Incluye instalación y desmontaje.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007008',
            'nombre' => 'Mant. y Rep. UPS',
            'descripcion' => 'Son los gastos por concepto de mantenciones y reparaciones de equipos UPS, para las unidades Judiciales y de administración del país. Incluye instalación y desmontaje de UPS.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007009',
            'nombre' => 'Mant. y Rep. PC',
            'descripcion' => 'Este catálogo es de uso exclusivo del Departamento de Informática y Computación del Poder Judicial. Son los gastos por concepto de mantenciones y reparaciones de PC, para las unidades Judiciales y de administración del país.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206007010',
            'nombre' => 'Otras Rep. Equipos Informáticos',
            'descripcion' => 'Son los gastos por concepto de mantenciones y reparaciones de equipos informáticos no considerados en las subasignaciones anteriores, para las unidades judiciales y de administración del país.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2206999000',
            'nombre' => 'Otros',
            'descripcion' => 'Son los gastos por concepto de mantenimiento y reparación de otras máquinas y equipos no incluidos en las asignaciones y subasignaciones anteriores de este ítem.',
            'item' => 2206,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001001',
            'nombre' => 'Servicios de Publicidad Televisiva y Audiovisual',
            'descripcion' => 'Son los gastos por concepto de publicidad contratada por medios televisivos, o de difusión audiovisual sujeto a la normativa del artículo 3º de la Ley Nº 19.896.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001002',
            'nombre' => 'Servicios de Publicidad Radial',
            'descripcion' => 'Son los gastos por concepto de publicidad contratada por medios radiales, sujeto a la normativa del artículo 3º de la Ley Nº 19.896.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001003',
            'nombre' => 'Servicios de Publicidad Medios Escritos',
            'descripcion' => 'Son los gastos por concepto de publicidad contratada por medios escritos, ya sea revistas, periódicos y/o similares, sujeto a la normativa del artículo 3º de la Ley Nº 19.896.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207001004',
            'nombre' => 'Otros Servicios de Publicidad',
            'descripcion' => 'Son los gastos por concepto de publicidad, sujeto a la normativa del artículo 3º de la Ley Nº 19.896, no contemplados en las otras subasignaciones.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207002000',
            'nombre' => 'Servicios de Impresión',
            'descripcion' => 'Comprende los gastos por concepto de servicios de impresión de afiches, folletos, revistas y otros elementos que se destinen para estos fines, reproducción de memorias, instrucciones, manuales y otros similares.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207003000',
            'nombre' => 'Servicios de Encuadernación y Empaste',
            'descripcion' => 'Comprende los gastos por concepto de servicios de encuadernación y empaste de documentos, informes, libros y similares.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2207999000',
            'nombre' => 'Otros',
            'descripcion' => 'Son los gastos por concepto de otros servicios de publicidad y difusión no contemplados en las asignaciones anteriores.',
            'item' => 2207,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001001',
            'nombre' => 'Servicio de Aseo Dependencias',
            'descripcion' => 'Son los gastos por concepto de contratación de servicios de limpieza en dependencias, para las distintas unidades Judiciales y administrativas del país.',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001002',
            'nombre' => 'Servicio de Fumigación y Sanitización',
            'descripcion' => 'Son los gastos por concepto de contratación de servicio de fumigación, sanitización y desinfección, para las distintas unidades Judiciales y administrativas del país.',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001003',
            'nombre' => 'Servicio Retiro Residuos, Basura, Escombros, Poda y Desmalez',
            'descripcion' => 'Servicio Retiro Residuos, Basura, Escombros, Poda y Desmalez',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208001004',
            'nombre' => 'Otros Aseo',
            'descripcion' => 'Otros Aseo',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208002001',
            'nombre' => 'Servicio de Guardias de Seguridad',
            'descripcion' => 'Servicio de Guardias de Seguridad',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208002002',
            'nombre' => 'Servicio de Alarmas y Monitoreo',
            'descripcion' => 'Servicio de Alarmas y Monitoreo',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208002003',
            'nombre' => 'Otros Vigilancia',
            'descripcion' => 'Otros Vigilancia',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208003000',
            'nombre' => 'Servicios de Mantención de Jardines',
            'descripcion' => 'Servicios de Mantención de Jardines',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007001',
            'nombre' => 'Pasajes y Movilización Normales Terrestres',
            'descripcion' => 'Pasajes y Movilización Normales Terrestres',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007002',
            'nombre' => 'Pasajes y Movilización Curs. Acad. Jud',
            'descripcion' => 'Pasajes y Movilización Curs. Acad. Jud',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007003',
            'nombre' => 'Pasajes y Movilización por Notificaciones',
            'descripcion' => 'Pasajes y Movilización por Notificaciones',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007004',
            'nombre' => 'Traslado de Valijas, Courier y Expedientes',
            'descripcion' => 'Traslado de Valijas, Courier y Expedientes',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007005',
            'nombre' => 'Permiso de Circulación y Patente',
            'descripcion' => 'Permiso de Circulación y Patente',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007006',
            'nombre' => 'Traslado por Nombramiento',
            'descripcion' => 'Traslado por Nombramiento',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007007',
            'nombre' => 'Otros Pasajes, Fletes y Bodegajes',
            'descripcion' => 'Otros Pasajes, Fletes y Bodegajes',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208007008',
            'nombre' => 'Pasajes y Movilización Normales Aéreos',
            'descripcion' => 'Pasajes y Movilización Normales Aéreos',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208008000',
            'nombre' => 'Salas Cunas y/o Jardines Infantiles',
            'descripcion' => 'Salas Cunas y/o Jardines Infantiles',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208010000',
            'nombre' => 'Servicios de Suscripción y Similares',
            'descripcion' => 'Servicios de Suscripción y Similares',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999001',
            'nombre' => 'Servicio de Coffe Break, Cocteleria y Banqueteria',
            'descripcion' => 'Servicio de Coffe Break, Cocteleria y Banqueteria',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999002',
            'nombre' => 'Servicio Suministro e Instalación de Señaletica (Letrero)',
            'descripcion' => 'Servicio Suministro e Instalación de Señaletica (Letrero)',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999003',
            'nombre' => 'Servicio para Plan de Difusion y Comunicación',
            'descripcion' => 'Servicio para Plan de Difusion y Comunicación',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999004',
            'nombre' => 'Servicio para Apoyo Digitalizacion',
            'descripcion' => 'Servicio para Apoyo Digitalizacion',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999005',
            'nombre' => 'Servicio De Aromatización y/o Odorización',
            'descripcion' => 'Servicio De Aromatización y/o Odorización',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2208999006',
            'nombre' => 'Otros Servicios Generales',
            'descripcion' => 'Otros Servicios Generales',
            'item' => 2208,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209001000',
            'nombre' => 'Arriendo de Terrenos',
            'descripcion' => 'Arriendo de Terrenos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002001',
            'nombre' => 'Arriendo de Inmuebles',
            'descripcion' => 'Arriendo de Inmuebles',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002002',
            'nombre' => 'Gasto Común Edificio Arrendado',
            'descripcion' => 'Gasto Común Edificio Arrendado',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002003',
            'nombre' => 'Arriendos de Bodega',
            'descripcion' => 'Arriendos de Bodega',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002004',
            'nombre' => 'Arriendos de Estacionamientos',
            'descripcion' => 'Arriendos de Estacionamientos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209002005',
            'nombre' => 'Otros Arriendos Edificios',
            'descripcion' => 'Otros Arriendos Edificios',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209003000',
            'nombre' => 'Arriendo de Vehículos',
            'descripcion' => 'Arriendo de Vehículos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209004000',
            'nombre' => 'Arriendo de Mobiliario y Otros',
            'descripcion' => 'Arriendo de Mobiliario y Otros',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209005000',
            'nombre' => 'Arriendo de Máquinas y Equipos',
            'descripcion' => 'Arriendo de Máquinas y Equipos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209006000',
            'nombre' => 'Arriendo de Equipos Informáticos',
            'descripcion' => 'Arriendo de Equipos Informáticos',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2209999000',
            'nombre' => 'Otros',
            'descripcion' => 'Otros',
            'item' => 2209,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210002001',
            'nombre' => 'Seguro Vehículos',
            'descripcion' => 'Seguro Vehículos',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210002002',
            'nombre' => 'Seguro Inmuebles',
            'descripcion' => 'Seguro Inmuebles',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210002003',
            'nombre' => 'Otros Seguros',
            'descripcion' => 'Otros Seguros',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210004000',
            'nombre' => 'Gastos Bancarios',
            'descripcion' => 'Gastos Bancarios',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2210999000',
            'nombre' => 'Otros',
            'descripcion' => 'Otros',
            'item' => 2210,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211001000',
            'nombre' => 'Estudios e Investigaciones',
            'descripcion' => 'Estudios e Investigaciones',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002001',
            'nombre' => 'Cursos de Capacitación CAPJ',
            'descripcion' => 'Cursos de Capacitación CAPJ',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002002',
            'nombre' => 'Cursos de Capacitación Academia Judicial',
            'descripcion' => 'Cursos de Capacitación Academia Judicial',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002003',
            'nombre' => 'Cursos de Capacitación Becas de Perfeccionamiento',
            'descripcion' => 'Cursos de Capacitación Becas de Perfeccionamiento',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211002004',
            'nombre' => 'Cursos de Capacitación Desarrollo Organizacional',
            'descripcion' => 'Cursos de Capacitación Desarrollo Organizacional',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211003000',
            'nombre' => 'Servicios Informáticos',
            'descripcion' => 'Servicios Informáticos',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999001',
            'nombre' => 'Servicio de Traducción y/o Interprete (Lengua)',
            'descripcion' => 'Servicio de Traducción y/o Interprete (Lengua)',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999002',
            'nombre' => 'Servicio de Revisión Técnica de Vehículos',
            'descripcion' => 'Servicio de Revisión Técnica de Vehículos',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999003',
            'nombre' => 'Servicio de Conducción y/o Reemplazo Oficial Asistente (Chof',
            'descripcion' => 'Servicio de Conducción y/o Reemplazo Oficial Asistente (Chof',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999004',
            'nombre' => 'Servicio de Mayordomía',
            'descripcion' => 'Servicio de Mayordomía',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999005',
            'nombre' => 'Servicio de Administración Técnica de Edificios',
            'descripcion' => 'Servicio de Administración Técnica de Edificios',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999006',
            'nombre' => 'Certificaciónes',
            'descripcion' => 'Certificaciónes',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999007',
            'nombre' => 'Gastos Comunes Edificio Propio',
            'descripcion' => 'Gastos Comunes Edificio Propio',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999008',
            'nombre' => 'Servicio de Cuidador',
            'descripcion' => 'Servicio de Cuidador',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999009',
            'nombre' => 'Mecánica de Suelos, Levantamiento Topógráfico y Tasaciones',
            'descripcion' => 'Mecánica de Suelos, Levantamiento Topógráfico y Tasaciones',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2211999010',
            'nombre' => 'Otros Servicios Profesionales',
            'descripcion' => 'Otros Servicios Profesionales',
            'item' => 2211,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212002000',
            'nombre' => 'Gastos Menores',
            'descripcion' => 'Gastos Menores',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212003000',
            'nombre' => 'Gastos de Representación, Protocolo y Ceremonial',
            'descripcion' => 'Gastos de Representación, Protocolo y Ceremonial',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212004000',
            'nombre' => 'Intereses, Multas y Recargos',
            'descripcion' => 'Intereses, Multas y Recargos',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212005000',
            'nombre' => 'Derechos y Tasas',
            'descripcion' => 'Derechos y Tasas',
            'item' => 2212,
            'estado' => 'Activo',
        ],
            [
            'catalogo' => '2212999000',
            'nombre' => 'Otros',
            'descripcion' => 'Otros',
            'item' => 2212,
            'estado' => 'Activo',
        ]
        ]);
    }
}
